sudo: required
services: 
  - docker
language: generic
before_install: 
  - docker build -t agarlapati/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true agarlapati/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: docker-react
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-107184343202Info"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
